remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: /assets/logo.PNG

search.button: true

back_to_top: true
back_to_top_text: "Back to top"


footer_content: Return to <a href="https://www.cloudm.io/resources">CloudM</a>
